### ISSUE TITLE
Unable to build vdoestimator

### ISSUE THREAD

**Issue by drckeefe** [dm-vdo/vdoestimator#28]
Hello.  I wasn't able to build vdoestimator and I believe it is do to recent changes in file locations and renames within vdo-devel.

make 
cc -D_GNU_SOURCE -Idownload/vdo-devel/src/c++/uds/src/uds -Idownload/vdo-devel/src/c++/uds/userLinux/uds -Idownload/lz4/lib     -c -o vdoestimator.o vdoestimator.c
vdoestimator.c:47:10: fatal error: uds.h: No such file or directory
   47 | #include "uds.h"
      |          ^~~~~~~
compilation terminated.

The make file might just needs to be updated?

Thanks.

**Comment by drckeefe** [comment]
@bgurney-rh fix works for me.  vdoestimator built fine, thank you.

**Comment by jwieleRH** [comment]
Fixed. Thanks.
